crowDidact/urls.py
from django.contrib import admin
from django.urls import include, path
from learningMaterial import urls as learning_urls
from learningMaterial import views as learning_views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(learning_urls))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learningMaterial/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('subjects/<str:subjectStr>/', views.subject, name='subjectPlus'),
    path('upload/', views.upload, name='upload'),
    path('new/', views.newSubject, name='newSubject'),
    path('notes/<str:noteStr>/', views.note, name='note'),
    path('', views.index, name='index')
]

learningMaterial/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

alphanumeric = RegexValidator(r'^[0-9a-zA-Z _]*$', 'Only alphanumeric, spaces, and underscores may be included')

class Subject(models.Model):
    name = models.CharField(max_length=150, unique=True, validators=[alphanumeric])

    def __str__(self):
        return self.name

    def humanRead(self):
        return self.name.replace('_', ' ')

class Blurb(models.Model):
    blurbText = models.TextField(max_length=50000)
    fromLink = models.URLField(max_length=600, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="blurb")
    def __str__(self):
        return self.subject.name

class YoutubeVideo(models.Model):
    link = models.URLField(max_length=600)
    favorites = models.IntegerField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.link

class LectureNote(models.Model):
    title = models.CharField(max_length=80,default="Note",blank=True,null=True,unique=True,validators=[alphanumeric])
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField()
    favorites = models.IntegerField(default=0)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def humanRead(self):
        return self.title.replace('_', ' ')

learningMaterial/forms.py
from django.forms import ModelForm
from .models import LectureNote, Subject

class uploadNoteForm(ModelForm):
    class Meta:
        model = LectureNote
        fields = ['title','image','subject']


class createSubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = ["name"]

learningMaterial/views.py
from django.shortcuts import render
from .models import Subject, LectureNote, YoutubeVideo, Blurb
from django.http import HttpResponse
from .forms import uploadNoteForm, createSubjectForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from .YTScrapper import YTScrape
from .WikiScrapper import wiki
from django.db import models

sub = Subject.objects.all().first()

def subject(request, subjectStr):
    if subjectStr:
        sub = Subject.objects.get(name__iexact=subjectStr)
    return render(request,"subject.html",{"subject":sub})

def index(request):
    return render(request,'index.html',{"subs":Subject.objects.all})

def note(request, noteStr):
    note = LectureNote.objects.get(title__iexact=noteStr)
    return render(request,"note.html",{"note":note})

def upload(request):

    if request.method == "POST":
        form = uploadNoteForm(request.POST, request.FILES, request.user)
        
        if form.is_valid():
            newTitle = form.cleaned_data["title"].replace(" ","_")
            obj = LectureNote(image=form.cleaned_data["image"],subject = form.cleaned_data["subject"],favorites=0,title=newTitle,author=request.user)
            obj.save()
            
            

            return HttpResponseRedirect(reverse(subject, args=[form.cleaned_data["subject"].name.replace(' ','_')]))
        
    else:
        form = uploadNoteForm()

    context = {
        'form':form
    }

    return render(request,"./form.html",context)

def newSubject(request):
    if request.method == "POST":
        form = createSubjectForm(request.POST, request.user)
        
        if form.is_valid():

            obj = Subject(name=form.cleaned_data["name"].replace(" ","_"))
            obj.save()
            
            blurb = Blurb(blurbText=wiki(form.cleaned_data["name"]),fromLink="https://wikipedia.org/",subject=obj)
            blurb.save()

            vidUrls = []

            for video in YTScrape(form.cleaned_data["name"] + "lecture","8"):
                if(video["url"] not in vidUrls):
                    vidUrls.append(video["url"])
                    lec = YoutubeVideo(subject=obj,link=video["url"], favorites=0)
                    lec.save()
            
            for video in YTScrape(form.cleaned_data["name"] + "course","6"):
                if(video["url"] not in vidUrls):
                    vidUrls.append(video["url"])
                    lec = YoutubeVideo(subject=obj,link=video["url"], favorites=0)
                    lec.save()

            return HttpResponseRedirect(reverse(subject, args=[form.cleaned_data['name'].replace(' ','_')]))
        
    else:
        form = createSubjectForm()

    context = {
        'form':form
    }

    return render(request,"./form.html",context)

learningMaterial/templates/base.html
<!DOCTYPE html>
<html>
<html lang="en">
<meta charset="utf-8">
<style>
  article {
    -webkit-flex: 3;
    -ms-flex: 3;
    flex: 3;
    background-color: #f1f1f1;
    padding: 10px;
  }

  figure {
    display: inline-block;
  }

  div.scrollmenu {
    background-color: #faf7be;
    overflow: auto;
    white-space: nowrap;
  }

  .center {
    margin: 0 auto;
    width: 400px;
  }

  div.scrollmenu a {
    display: inline-block;
    align: center;
    color: white;
    text-align: center;
    text-decoration: none;
  }

  div.scrollmenu a:hover {
    background-color: #777;
  }

  pre {
    font-family: Times, "Times New Roman", serif;
  }

  .padding {
    padding: 35px;
  }

  .margin {
    margin-left: 2%;
    margin-right: 2%;
    margin-top: 4%;
    margin-bottom: 1.5%;
  }

  .contentbox {
    display: inline-block;
    color: #f00;
    line-height: 100px;
    text-align: center;
    box-sizing: border-box;
    margin-left: 50px;
    margin-right: 8px;
  }

  .contentboxV {
    white-space: nowrap;
    display: inline-block;
    height: 100%;
    text-align: center;
    height: 100%;
    vertical-align: middle;
    position: relative;
    display: inline-block;
    positions: absolute;
    color: #f00;
    background-color: #FFFDD0;
    line-height: 100px;
    text-align: center;
    box-sizing: border-box;
    margin-top: 50px;
    margin-left: 50px;
    margin-right: 8px;
    height: 275px;
    width: 225px;
  }

  .helper {
    display: inline-block;
    height: 100%;
    vertical-align: middle;
  }

  img {
    vertical-align: middle;
    max-width: 100%;
    max-height: 100%;
  }

  button {
    display: inline-block;
    vertical-align: bottom;
    margin-right: -50px;
  }

  .vertical-menu {
    width: 200px;
    height: 150px;
    overflow-y: auto;
  }

  .vertical-menu a {
    background-color: #eee;
    color: black;
    display: block;
    padding: 12px;
    text-decoration: none;
  }

  .vertical-menu a:hover {
    background-color: #ccc;
  }

  .vertical-menu a.active {
    background-color: #4CAF50;
    color: white;
  }

  .verticaldiv {
    margin-top: 50px;
  }

  .horizontalScrollable {
    overflow-x: auto;
    overflow-y: hidden;
    white-space: nowrap;
  }
</style>

<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
  
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <main>
    
    


    <div class="container-fluid">
      <div class="row" style="background-color:darkseagreen;">
        <div class="col-sm-4">

            <h1>
              <a href="/">CrowDidact</a>
            </h1>
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4" style="justify-content: right;">
          <button type="button" class="btn btn-light" style="margin-top: 1.5%;"><a href="/new">New Subject</a></button>
          <button type="button" class="btn btn-light" style="margin-top: 1.5%;"><a href="/upload">Upload Note</a></button>
        </div>

    </div>
      <div class="w-75 p-3" style="margin-left: auto; margin-right: auto;">

        {% block content%}
        {% endblock %}

      </div>
    </div>


  </main>
</body>

</html>

learningMaterial/templates/form.html
{% extends "base.html" %}
{% block content %}

<div class="container">

    <h1>Enter Data: </h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        {% for field in form %}
        <fieldset class="control-group">
            <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
            <div class="controls">
                {{ field }}
                <p class="help-text">{{ field.help_text }} </p>
            </div>
        </fieldset>
        {% endfor %}
        <div class="form-group">
            <button type="submit" style="margin-left: 5%">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

learningMaterial/templates/index.html
{% extends "base.html" %}
{% block content %}

<br/>
    <h1>Our Subjects</h1>
    <br/>

<div class="row">

    

    {% for subject in subs %}
    <div class="col-sm-4 d-flex justify-content-center" style="padding-top: 3%; padding-bottom: 3%; outline: 2px solid #ccc; justify-content: center;">
        <h2><a href="/subjects/{{subject.name}}">{{ subject.humanRead }}</a></h2>
    </div>

    {% endfor %}




</div>


{% endblock content %}

learningMaterial/templates/note.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col" align="center">
        <img src="{{ note.image.url }}" alt="The note" class="image-responsive"
            style="margin-left: auto; margin-right: auto;">
    </div>
</div>

{% endblock %}

learningMaterial/templates/subject.html
{% extends "base.html" %}
{% block content %}
<article style="padding-top: 4%;">
    <h1 style="margin-left: 1%;"><a href="https://wikipedia.org/">{{ subject.humanRead }}</a></h1>

    <p style="margin-left: 3%;">
      {{ subject.blurb.first.blurbText }}
    </p>

  </article>

  <h2 class="margin">Lectures</h2>
  <div class="horizontalScrollable">
    <div class="row flex-row flex-nowrap">

      {% for video in subject.youtubevideo_set.all %}
      <div class="col-sm-6">
        <iframe width = "530" height = "300" src="{{video.link}}" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen></iframe>
      </div>
      {% endfor %}
    </div>
  </div>
  <br/>
  <h2 class="margin">Notes</h2>
  <div class="row">

    {% for note in subject.lecturenote_set.all %}
      <div class="col-sm-4" style="margin-top:4%; margin-bottom: 2%;">
        <a href="../../notes/{{ note.title }}">
          <span class="helper"></span><img
            src="{{ note.image.url }}">
        </a>
        <br />
        <button class="btn btn-primary">Like</button>
        {{ note.humanRead }}
      </div>

    {% endfor %}

    <br/>
    <br/>


  </div>
  {% endblock %}

learningMaterial/templates/subjectBase.html
<!DOCTYPE html>
<html>
<head>

</head>

<body>
    <h1> Its working! Im inside templates </h1>

    <p>{{ subject }}</p>
    <p>{{ subject.name }}</p>
    <p>{{ subject.blurb.first.blurbText }}</p>


    {% for video in subject.youtubevideo_set.all %}
    <iframe width="963" height="722" src="{{ video.link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    {% endfor %}
    {% for note in subject.lecturenote_set.all %}
    <img src="{{ note.image.url }}"></img>
    {% endfor %}
</body>

</html>

learningMaterial/templates/uploadNote.html
<html>

<body>
    
<form method="POST" enctype="multipart/form-data">
    {% csrf_token%}

    <fieldset class="form-group">
        {{ form.as_p }}
    </fieldset>
    <div class="form-group">
        <button type="submit">Button</button>
    </div>
</form>

</body>

</html>